### ISSUE TITLE
Discuss implementing new website design in Flutter

### ISSUE THREAD

**Issue by ApolloZhu** [UWAppDev/uwappdev.github.io#11]
We could invite club members to contribute

**Comment by XinyiXiang** [comment]
Let's talk about #86:

1. What's impeding RSS subscription from current community website?
2. Shall we consider set up blog views on club website? Then add RSS?

**Comment by ApolloZhu** [comment]
When do we expect this discussion to happen?

**Comment by ApolloZhu** [comment]
The team has agreed to switch to Flutter implementation, see future developments in https://github.com/UWAppDev/uwappdev.github.io/tree/flutter
